### PR TITLE
Add fabric-server-node.

### PR DESCRIPTION
**Pull request by 5sWind**
Signed-off-by: Hengming Zhang <fiveswind@gmail.com>

## Checklist for Hyperledger Lab Proposal PR

- [ ] Read [README.md](https://github.com/hyperledger-labs/hyperledger-labs.github.io/blob/master/README.md) carefully
- [ ] Make sure your changes are committed with the proper sign-off
- [ ] Use the labs name as the PR title
- [ ] Copy the short description of the proposal as the description of the PR
- [ ] Remove this checklist section
- [ ] Submit your PR and the labs stewards will review your proposal

### CODE REVIEW

**Comment by tkuhrt** [comment]
This sponsor must be
> a maintainer of one of the Hyperledger projects, a TSC member or a WG chair

Can you confirm David meets this requirement?

**Comment by 5sWind** [comment]
> This sponsor must be
> 
> > a maintainer of one of the Hyperledger projects, a TSC member or a WG chair
> 
> Can you confirm David meets this requirement?

Yes.

**Comment by 5sWind** [comment]
@dexhunter.

**Comment by 5sWind** [comment]
@tkuhrt @lehors @vipinsun @trbs I've replaced the sponsor to a Fabric python SDK maintainer.

**Comment by dexhunter** [comment]
I agree.

**Comment by 5sWind** [comment]
@tkuhrt I've migrated all my commits to one commit with proper signed-off: `Signed-off-by: Hengming Zhang <fiveswind@gmail.com>`
Please transfer older repo to new one in hyperledger-labs.

**Pull request merged**
