### PR TITLE
add Hyperledger Fabric Based Access Control

### PR DESCRIPTION
**Pull request by RafaelAPB**

### CODE REVIEW

**Comment by RafaelAPB** [comment]
@ryjones closed PR #77, opened this one. DCO should be fine now. Thanks for the help.

**Comment by lehors** [comment]
This sure looks like something worthy of a hyperledger lab so I'm all for it but the description could be expanded a bit. What kind of access control and information are you talking about? Information stored where?
And I don't think you only mean "to discourage unauthorized accesses", do you? Don't you rather mean "prevent"??

**Comment by RafaelAPB** [comment]
@lehors Thank you for your feedback. I have expanded the description a bit, hope it's clearer now. 

This project aims to mediate the access control flow coming from a centralized system. Therefore, it does not prevent completely unauthorized accesses. This tackles the use case where a user can access a different set of files, but should only do that in certain circumstances. On the other hand, it discourages illicit accesses, as the system administrators are not able to tamper the access logs (if applicable). This way, a user can not refute his or her access requests. 

If that does not answer your questions, please let me know!

**Comment by RafaelAPB** [comment]
@tkuhrt, @vipinsun if you have any queries, please let me know.

**Comment by lehors** [comment]
Thanks for the explanation. +1 for me.

**Comment by trbs** [comment]
+1 from me as well.

**Comment by RafaelAPB** [comment]
@tkuhrt @vipinsun is there anything missing?
Thanks in advance!

**Comment by vipinsun** [comment]
> @tkuhrt @vipinsun is there anything missing?
> Thanks in advance!

Hi,
Although you gave @lehors  an explanation; I still find the lab description opaque. Are you going to follow the design in the second paper (Maesa, Mori & Ricci)w.r.t implementing ABAC using smart contracts. Please refer to this and make the lab description clearer. It is a good project to clear the thinking on ABAC, especially if you can record the Attributes, The rules etc in Smart Contracts/coupled with the ledger itself mediated by the Access management smart contract. I could not understand how this system will help (is this purely for auditing purposes) or will it also function as the Policy Enforcement Point? Are you going to use ABAC or some other scheme. Making these clearer will be beneficial for people who want to engage with this lab.
Vipin
Is there existing code? And is Ry the sponsor?

**Comment by RafaelAPB** [comment]
@vipinsun thank you for your feedback.
This project is in the context of the Hyperledger Summer Internship program. The project plan is not completely defined yet. 

Our work will be based on Maesa et al., directed to the context of Hyperledger Fabric. 
This system enhances auditability and access control policy enforcement, as it embeds the Policy Decision Point and Policy Information Point. The Policy Enforcement Point is case-dependent, although we can try to create an abstraction on top of Fabric to try to standardize it. We are probably going to use ABAC, as allows fine-grain control, but other options can be taken. We are still researching.

More than auditability, this project allows decentralizing the access control process, while having the necessary privacy measures, if needed. This is particularly useful in a scenario with multiple stakeholders involved (i.e. different public organizations), using one information system.

We are going to maintain a detailed wiki with the design decisions and an updated project plan, for transparency and auditability. Any opaqueness results from on-going decisions.

@ryjones volunteered to sponsor our lab. There is no code yet, as we are currently researching.
Hope this clarifies. In case of any doubt feel free to ask. 
Thanks,
Rafael

**Pull request merged**
