### PR TITLE
weaver-dlt-interoperability

### PR DESCRIPTION
**Pull request by VRamakrishna**
Signed-off-by: VRamakrishna <vramakr2@in.ibm.com>

_Short Description_: A platform, a protocol suite, and a set of tools, to enable interoperation for data sharing and asset movements between independent networks built on heterogeneous blockchain, or more generally, distributed ledger, technologies, in a manner that preserves the core blockchain tenets of decentralization and security.

### CODE REVIEW

**Review by lehors — APPROVED** [review]
Happy to see this coming to Hyperledger. Thanks!

**Review by vipinsun — APPROVED** [review]
Sounds well thought out. I see that there is existing code. No reference is given. Is existing code going to be migrated to labs? You need to have DCO on that. On another note I would like to have any kind of architecture diagram so that it can be presented as a use case in DCGI a standards initiative in ITU/Stanford. Please contact me separately for that @VRamakrishna

**Comment by vipinsun** [comment]
Merged the commit!

**Comment by tkuhrt** [comment]
Created https://github.com/hyperledger-labs/weaver-dlt-interoperability and invited initial committers

**Pull request merged**
