### PR TITLE
Yaz.ethercluster proposal

### PR DESCRIPTION
**Pull request by YazzyYaz**
Signed-off-by: Yaz Khoury yaz@etccooperative.org

Adds the Ethercluster proposal to Hyperledger Labs

### CODE REVIEW

**Comment by YazzyYaz** [comment]
@vipinsun I fixed the DCO issues, thanks for pointing it out.

**Comment by bobsummerwill** [comment]
Excellent - thanks so much for the approval!

What is our next step here?   We are going to need to do the import into https://github.com/hyperledger-labs/ethercluster.

That could just be a straight git clone, because @YazzyYaz is the only contributor to date.   So only he would just need to do the DCO sign-off.    I know from my prior work on the cpp-ethereum relicensing attempt that it might well be wise for us to simplify things here by just importing a flattened snapshot with no history, and with Yaz doing the DCO-sign off for that initial commit.

@YazzyYaz is going to need commit rights.  How do you want to manage this, @ryjones?  Best wishes!

**Comment by ryjones** [comment]
@YazzyYaz you have write access to https://github.com/hyperledger-labs/ethercluster . Please fork it, copy over your files, add them and do a git commit -s. Then do a pull request. If you use [hub](https://hub.github.com), this is pretty easy.

**Comment by YazzyYaz** [comment]
@ryjones thank you so much for your help!

I've made the PR, all as one commit signed off by me https://github.com/hyperledger-labs/ethercluster/pull/2

**Pull request merged**
