### PR TITLE
crypto-lib Proposal

### PR DESCRIPTION
**Pull request by hartm**
Adding crypto-lib proposal for labs

### CODE REVIEW

**Comment by tkuhrt** [comment]
LGTM +1

**Comment by lehors** [comment]
+1!

**Comment by trbs** [comment]
LGTM +1

One request though, before merging could you update the title and description of the PR ? just so that later it's easier to find it / manage.

**Comment by vipinsun** [comment]
+1 - same comment as trbs

**Comment by tkuhrt** [comment]
I made the changes to the title and description. I will merge this and get the new repo set up later today.

**Pull request merged**
