### PR TITLE
Aries Agent Deployment Lab

### PR DESCRIPTION
**Pull request by monar24**
This lab focuses on deploying Hyperledger Aries agents using Kubernetes. The project includes Kubernetes charts and Helm packages for easy and scalable deployment of Aries agents in a cloud environment, specifically designed for AWS using Amazon EKS. It can be adjusted for use with other cloud providers as well. Also included is an agent controller.

### CODE REVIEW

**Review by tkuhrt — APPROVED** [review]
Looks like an interesting lab. It would be great if you could also connect with the Bevel maintainers to determine if there might be a fit for the Helm charts to fall into their work. cc: @sownak @suvajit-sarkar

**Comment by sownak** [comment]
Agreed. Bevel is gradually transforming into a Helm repo for all DLT charts, so this should be part of Bevel.

**Comment by monar24** [comment]
This lab includes 2 repositories: one is a multi-tenant agent controller, the other is the agent charts. 
It sounds like the charts are to be moved to bevel. I can raise a separate PR for Bevel and then update this lab to be focused on the multi-tenant agent.  Should I create a new PR or update this one?

**Comment by tkuhrt** [comment]
Thanks, @monar24 for being open to contributing to Hyperledger Bevel. This looks like a great lab. Looking forward to getting it approved. @hyperledger-labs/lab-stewards : Please have a look and see what you think.

**Review by nidhi-singh02 — APPROVED** [review]
Seems great to me.

**Comment by sownak** [comment]
@monar24 Thanks for the contribution to Bevel. I have provided some comments that needs to be addressed before the chart can be merged. Also the chart name has to be defined so that it can be published via Bevel release process. Appreciate the contribution a lot, but also we do not want it to be just one time contribution, please ensure that the chart is maintained as well.

**Comment by monar24** [comment]
> @monar24 Thanks for the contribution to Bevel. I have provided some comments that needs to be addressed before the chart can be merged. Also the chart name has to be defined so that it can be published via Bevel release process. Appreciate the contribution a lot, but also we do not want it to be just one time contribution, please ensure that the chart is maintained as well.

Thanks @sownak, just saw the feedback and have responded on the Bevel PR 

Also thanks @tkuhrt and @nidhi-singh02 for the approval 👍

**Pull request merged**
