### PR TITLE
update ElectrodoDoc's lab description

### PR DESCRIPTION
**Pull request by andrii482**
## Checklist for Hyperledger Lab Proposal PR

- [ ] Read [README.md](https://github.com/hyperledger-labs/hyperledger-labs.github.io/blob/master/README.md) carefully
- [ ] Make sure your changes are committed with the proper sign-off
- [ ] Use the labs name as the PR title
- [ ] Copy the short description of the proposal as the description of the PR
- [ ] Remove this checklist section
- [ ] Submit your PR and the labs stewards will review your proposal
- [ ] Ask your sponsor to confirm sponsorship by stating so in a comment to the PR

### CODE REVIEW

**Review by knagware9 — COMMENTED** [review]
its good lab project focusing on ESG & climate change. We can explore synergies in Hyperledger Climate SIG, there is one lab for carbon accounting so if we can explore this lab in same manner.

https://wiki.hyperledger.org/display/CASIG/
https://wiki.hyperledger.org/display/CASIG/Carbon+Accounting+and+Certification+WG
https://github.com/hyperledger-labs/blockchain-carbon-accounting

**Comment by andrii482** [comment]
> Hi, @andrii482 : It looks like in #204 we approved this lab, but never transferred the repository to the Hyperledger Labs organization. Do you plan to transfer the existing repo from the 482solutions organization to Hyperledger Labs?

Hi, @tkuhrt: Yep. We want to make migration

**Comment by ryjones** [comment]
@andrii482 transfer [the repo](https://github.com/482solutions/ElectrodoDoc-meta) to me (@ryjones).

**Review by ryjones — APPROVED** [review]

**Comment by andrii482** [comment]
> @andrii482 transfer [the repo](https://github.com/482solutions/ElectrodoDoc-meta) to me (@ryjones).

done.

Can also please someone check where exactly new ElectrodoDoc page appear after approving this #244  pull-request and merge

**Comment by ryjones** [comment]
https://github.com/hyperledger-labs/Electrodo.Docs https://labs.hyperledger.org/labs/ElectrodoDoc.html

**Comment by andrii482** [comment]
Hello @ryjones 

How I can make pull-reguest in https://github.com/hyperledger-labs/Electrodo.Docs  ?

now I get this error when try to push code in new branch on in `main` :point_down: 
```
remote: Permission to hyperledger-labs/Electrodo.Docs.git denied to andrii482.
fatal: unable to access 'https://github.com/hyperledger-labs/Electrodo.Docs.git/': The requested URL returned error: 403
```

**Pull request merged**
