### PR TITLE
Blockchain Verifier

### PR DESCRIPTION
**Pull request by shimos**
## Short Description

A tool to check and verify the integrity of ledgers and the correctness of smart contracts

Signed-off-by: Taku Shimosawa <taku.shimosawa@hal.hitachi.com>

### CODE REVIEW

**Comment by trbs** [comment]
@hartm could you confirm your sponsership ?

**Comment by hartm** [comment]
Happy to confirm sponsorship.  Thanks!

**Comment by shimos** [comment]
@trbs Thank you for the review. We are implementing it in a plugable way so that it can run with multiple blockchain platforms.
While it is true that it currently supports only Fabric, we consider that our next target will be Indy (but with no concrete date yet),
and we anticipate contributions for other platforms.

**Comment by trbs** [comment]
@shimos thank you for the response and explanation 

Think your proposal looks fine to me and an interesting project. 
Any further thoughts on naming things in this context is more a question to other stewards then your proposal :-)

Have an awesome labs ;-)

**Comment by vipinsun** [comment]
Looks like all necessary approvals are in so I merged.

**Pull request merged**
