### PR TITLE
sgurary: added labs/sawtooth-secure-transaction-families.md for pull …

### PR DESCRIPTION
**Pull request by sgurary**
…request
Hi, Creating the new pull request as discussed with 
Tracy Kuhrt
@tkuhrt

Thanks, Shefy
Signed-off-by: Shefy Gur-Ary <shefy.gurary@intel.com>

### CODE REVIEW

**Comment by trbs** [comment]
LGTM

**Comment by sgurary** [comment]
@trbs @tkuhrt 

Thanks, so what's the next step?

**Comment by tkuhrt** [comment]
@hyperledger-labs/lab-stewards : This is a continuation of #13 that had some DCO issues. It looks like those are now resolved. Any other comments on this lab proposal?

**Comment by lehors** [comment]
LGTM +1

**Comment by tkuhrt** [comment]
With 2 +1's, we will create a lab and then merge this PR.

**Comment by tkuhrt** [comment]
Created https://github.com/hyperledger-labs/sawtooth-secure-transaction-families

**Comment by sgurary** [comment]
@tkuhrt 

Hi, 

We got a request to change the name from legal. We are still waiting for final approval on the name. 
Please note that Dan Middleton (Intel sponsor) took the action to discuss and clear the name with Hyperledger labs (which is approved by Intel legal).

In addition, we noticed that the details in the readme file (https://github.com/hyperledger-labs/sawtooth-secure-transaction-families) are not the details from our request. 

We would also provide a new readme file with all the updated details. (Ronen Shem-Tov is currently working on it.)

Thanks, Shefy

**Pull request merged**
