### PR TITLE
Hyperledger Labs proposal for a did:webs implementation

### PR DESCRIPTION
**Pull request by swcurran**
Signed-off-by: Stephen Curran <swcurran@gmail.com>

Proposal for a Hyperledger Labs repo for an implementation of the `did:webs` DID Method for use with Hyperledger Aries agents and for issuers, holders and verifiers of Hyperledger AnonCreds verifiable credentials.

I'm the sponsor of the proposal (TOC Member) and will be one of the initial maintainers of the Lab.

FYI:

- @2byrds
- @dhh1128
- @pfeairheller
- @peacekeeper

### CODE REVIEW

**Review by tkuhrt — APPROVED** [review]

**Review by vipinsun — APPROVED** [review]
LGTM

**Comment by 2byrds** [comment]
Fantastic!

**Comment by 2byrds** [comment]
@swcurran I have merged Markus' PR in the WebOfTrust repo. We are ready to bring that repo to the new HL Labs repo. https://github.com/WebOfTrust/did-keri-resolver. Please give Markus and I write privileges.

**Comment by swcurran** [comment]
@ryjones — can you please work with @peacekeeper (Markus Sabadello) to move the repo from RWoT to Hyperledger Labs?  I’m not sure who owns it at RWoT, so it might take some sorting out...

**Comment by 2byrds** [comment]
@ryjones I have write access in WebOfTrust repo

**Comment by swcurran** [comment]
@2byrds — I’m guessing that you need Owner privileges to the repo in order to be able to transfer it.

**Comment by ryjones** [comment]
@2byrds you'll need to transfer it to me, `ryjones`, so I can move it

**Comment by 2byrds** [comment]
@ryjones I talked to all devs involved, we agree that it will be faster/easier for you to either:
Create a fork from the current repo https://github.com/WebOfTrust/did-keri-resolver
OR
Create a new repo in HL Labs called did-webs-resolver and we'll treat it as an upstream repo and push our code up there

**Comment by ryjones** [comment]
@2byrds would this involve smashing all the commits? A few aren't signed off

**Comment by 2byrds** [comment]
@ryjones if smashing all the commits makes is needed, we'er willing to go that route.

**Comment by ryjones** [comment]
@2byrds please smash the repo (probably in your personal account?) and transfer it to me. Don't forget the DCO signoff :)

**Comment by 2byrds** [comment]
@ryjones https://github.com/2byrds/did-webs-resolver has been transferred to you. Let me know if you need anything and thank you!

**Pull request merged**
