### PR TITLE
Update proposal-template.md

### PR DESCRIPTION
**Pull request by FedeCune**
Good evening,
this is the proposal to enter the Hyperledger Labs with our IBAN Portability project (FORFIRM's team). To date we have developed the REST API code and we would like to develop the second version in Hyperledger Fabric.

Pending feedback, best regards

### CODE REVIEW

**Comment by tkuhrt** [comment]
It appears that you missed this step:
```
Fill out the Proposal Template and save it into the labs subdirectory under the name of your lab, such as mynewlab.md. It is expected that your lab repository will have the same name so keep that in mind.
```

You need to copy the `proposal-template.md` to a new file under the `labs` subdirectory, and then fill it out.

In addition, you missed the DCO sign-off that is required. Provide the `-s` option to `git commit`.

I recommend closing this PR and doing another PR.

**Comment by vipinsun** [comment]
Federica, do you need help to do what Tracy suggests above? If so reach out to me and I can. But we do need  DCO sign-off

**Comment by vipinsun** [comment]
Federica,
If you are planning to contribute already existing code, the DCO (or developer certificate of origin) says that either you have the right to contribute the code or the people who authored the code are giving you permissions, so that we have provenance on the code; see https://developercertificate.org/. As Tracy says above using the -s option with the command line git commit will take care of this. In addition the suggestion she gave is to close this PR and re-open another PR with your proposal template , following the directions that she has given above. Once that is done and the PR is approved, you can prove with your git url that you are under hyperledger labs.
Best,
Vipin

**Comment by tkuhrt** [comment]
@FedeCune : You can also see the information under https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/42/checks that will give you the command-line options to fix the DCO issue on your branch. You will also need to ensure that you are creating a new file and not modifying the existing template file.

**Comment by ryjones** [comment]
I propose we close this particular PR

**Comment by ryjones** [comment]
Please re-open as required

**Pull request closed without merging**
