### PR TITLE
Operations Smart Contract for Hyperledger Fabric

### PR DESCRIPTION
**Pull request by satota2**
# Short Description

Operations Smart Contract (OpsSC) is a smart contract-based system operation tool for Hyperledger Fabric-based systems,
which aims to enable efficient decentralized system operations across multiple organizations.

Signed-off-by: Tatsuya Sato <Tatsuya.Sato@hal.hitachi.com>

### CODE REVIEW

**Review by lehors — APPROVED** [review]
LGTM!

**Comment by trbs** [comment]
David Enyeart could you please confirm sponsorship ?

**Comment by satota2** [comment]
@denyeart Could you confirm this?

**Comment by denyeart** [comment]
I confirm that I am the sponsor!

**Review by trbs — APPROVED** [review]

**Comment by tkuhrt** [comment]
@satota2 : Can you transfer the [existing repo](https://github.com/satota2/fabric-opssc/commits/master) to @tkuhrt. I will then transfer the repo to the hyperledger-labs organization and set up the team with the committers you specified.

**Comment by satota2** [comment]
@denyeart Thank you for your confirmation!
@trbs @lehors @tkuhrt Thank you for your approving!

@tkuhrt I just transferred the repository to you. Could you confirm it?

**Comment by tkuhrt** [comment]
@satota2 : Transferred to https://github.com/hyperledger-labs/fabric-opssc, created a team, and added branch rules to ensure DCO exists on the commits. You should be good to go.

**Comment by satota2** [comment]
@tkuhrt Thank for your support!

**Pull request merged**
