### PR TITLE
Benchmarking Cross-Chain Bridges

### PR DESCRIPTION
**Pull request by RafaelAPB**

### CODE REVIEW

**Comment by RafaelAPB** [comment]
@vipinsun or @knagware9 would you be able to sponsor this lab?

**Comment by tkuhrt** [comment]
@RafaelAPB : How is this different than #240

**Comment by RafaelAPB** [comment]
@tkuhrt my mistake - it's a duplicate. Let's keep this one open.

**Review by tkuhrt — APPROVED** [review]

**Review by vipinsun — APPROVED** [review]
You can add me as sponsor if needed. Sponsor is optional.

**Pull request merged**
