### PR TITLE
Fabric documentation translation to Chinese

### PR DESCRIPTION
**Pull request by lujjiang**
Signed-off-by: Jiang Lu lujjiang@cn.ibm.com

### CODE REVIEW

**Comment by lehors** [comment]
Actually, you can also use a TSC member as a sponsor and I will be happy to be your sponsor so feel free to use my name. :-)

**Comment by trbs** [comment]
I'm in favor of translations 👍 

Have one suggestion; In the pre-existing repository, I would add a little paragraph of English in the README explaining the repository and how to get in touch. This makes it easier to communicate.

And one question; Can you in the proposal describe how this project/lab will make sure that the translation is kept up to date ? I think it's important with translation efforts that there is some kind of "guarantee" that these translations we not go stale as the source documentation progresses.

With that I'm +1

**Comment by lujjiang** [comment]
Thanks for the comments. Have updated the proposal. Please review.

**Comment by lehors** [comment]
The DCO error report is bogus. I think this is now good to go.
+1 for me.

**Comment by tkuhrt** [comment]
Lab renamed to fabric-docs-cn.md in PR #39. The existing repository does not have appropriate DCO sign-offs so will need to be brought over to lab manually.  Created https://github.com/hyperledger-labs/fabric-docs-cn and added initial committers.

**Pull request merged**
