### PR TITLE
Update README.md with link to DCO

### PR DESCRIPTION
**Pull request by jeremiah**
Signed-off-by: Jeremiah C. Foster <jeremiah@jeremiahfoster.com>

### CODE REVIEW

**Comment by tkuhrt** [comment]
LGTM

**Comment by jeremiah** [comment]
For the sake of clarification, *every* commit in our repo that is proposed to Hyperledger has to have the signed-off-by line? Otherwise we have to squash the commits into a new commit with a signed-off-by line? Isn't it enough, at least for DCO purposes, to have a single sign-off per developer? If a developer has signed off on the DCO once, isn't that sufficient?

**Comment by tkuhrt** [comment]
Every incoming commit has to have DCO.

**Comment by jeremiah** [comment]
Okay. Understood. I think the plan then is for us to squash and have me sign.

**Comment by tkuhrt** [comment]
Something weird happening with the status check here. I am not sure what else it is waiting on. I would like to merge this PR.

**Pull request merged**
