### PR TITLE
Fablo

### PR DESCRIPTION
**Pull request by Hejwo**
Setting up and running a custom Hyperledger Fabric network is hard. The main goal of Fablo is to make this process easy, straightforward and accessible. It transforms a single configuration file to running network.

### CODE REVIEW

**Review by tkuhrt — APPROVED** [review]
This looks like an acceptable lab. I did notice that the DCO signoff in the existing repository does not exist. Hyperledger requires that all contributed code has a DCO sign off. There are two options that we normally consider for fixing this:

1. Amend existing commits in the repository to include DCO sign off
2. Manually transfer the code from the existing repo to the newly created repo within the hyperledger-labs GitHub organization.

In addition, you may be interested in existing labs which do similar things: minifab, blockchain-automation-framework.

**Comment by Hejwo** [comment]
Hi, thanks for replay and approval. 
We'll try to go with option 1 - fixing commits. Will let you know.

**Review by lehors — APPROVED** [review]
LGTM. I think it's worth pointing out that several efforts exist in that space such as Cello and Minifabric and it would be good to explore possible collaboration.

**Comment by dzikowski** [comment]
Thanks! We also updated all commits in our repo to include DCO sign off and enforced the DCO sign offs in our CI.

**Comment by Hejwo** [comment]
Awesome, thanks for merging!  
As it was said we signed off all commits in pre-existing repository and are ready for next steps. Let us know if we need to do something more.  
  
When it comes to other similar efforts we will definitely explore the topic.  
We thought a lot about integration with BAF, but will review other options too.

**Comment by tkuhrt** [comment]
Hi, @dzikowski and @Hejwo : Can you please transfer your repository to @rjones so that he may transfer it to the hyperledger-labs github organization?

**Pull request merged**
