### PR TITLE
fabric-docs-ml

### PR DESCRIPTION
**Pull request by ODOWDAIBM**
…abric

Signed-off-by: Anthony O'Dowd <a_o-dowd@uk.ibm.com>

A project to translate the Fabric documentation into Malayalam.

### CODE REVIEW

**Comment by lehors** [comment]
@ODOWDAIBM you need to rename the template file, in this case to fabric-docs-ml.md, so that it doesn't replace the template when we merge your PR.

**Comment by lehors** [comment]
I hereby confirm sponsorship of this lab.

**Comment by tkuhrt** [comment]
Long term, I would like to see all of the different translation of documentation for Fabric combined under a fabric-docs folder and for all of the option to be provided under the same hyperledger-fabric.readthedocs.io location with the /en /ml /cn providing the respective translation. In the meantime, I support this lab, and I will approve once the proposal is put under `labs/fabric-docs-ml.md`

**Comment by vipinsun** [comment]
So glad to see this as Malayalam is my mother tongue. It is also the longest palindrome in the OED

**Comment by lehors** [comment]
I had a chat with @ryjones who was asking, quite astutely I must say, why this isn't simply part of the Fabric project.

Because Fabric maintainers were uncomfortable to take ownership of something they couldn't understand they resisted bringing the Chinese translation project into Fabric. I never thought this was the right thing to do though and I think it is time this question gets looked at again. I will bring it up to the Fabric maintainers.

In the meantime I think getting the lab setup is a good first step to capitalize on the will of interested parties to get the effort going.

**Comment by ODOWDAIBM** [comment]
I had a good call with Aneena, Jubilant and the Malayalam team this morning, showing the outline repo, and options for translations. @tkuhrt , to your point, I too would like to see this all incorporated under the same (i.e. Fabric) repo; as @lehors says, this is a starting point.  Tracy, I think your comment is important through, as it implies using PO/POT files, which I have showed the team how to use -- the repo has been set up with the appropriate gettext/locale information. 

If the repo is approved, Aneena and I will set up a RTD public build so that the Malayalam team can collaborate and have a working public doc site -- with the intention to integrate into the Fabric docs website once it reaches a level of completeness.

**Comment by ODOWDAIBM** [comment]
@lehors Sorry for the silly mistake Arnaud -- I moved the template to the correct directory, with the correct name.  Thanks for the pointer; hopefully should be OK now.

**Comment by ryjones** [comment]
@ODOWDAIBM let me know if you want a new repo, or you want to transfer the previous repo. If you want to transfer it, please transfer it to me - `ryjones` - or Tracy - `tkuhrt` - and either of us can transfer it to the `hyperledger-labs` org, enable DCO, and all that.

**Comment by ODOWDAIBM** [comment]
Thank you @ryjones and @tkuhrt. I transferred the fabric-docs-ml repo to you Ry.

**Pull request merged**
