### PR TITLE
adding umbra proposal

### PR DESCRIPTION
**Pull request by dhuseby**
This is the labs proposal for the Umbra project.

Signed-off-by: Dave Huseby <dhuseby@linuxfoundation.org>

### CODE REVIEW

**Comment by tkuhrt** [comment]
Can you be a sponsor, @dhuseby?  Labs wiki page says "Sponsor (i.e. a maintainer of one of the Hyperledger projects, a TSC member or a WG chair)"

**Comment by vipinsun** [comment]
Hi Mr. Huseby,
Great setup for limited experimentation. However, there is nothing specific here. Some questions
The short description says
 
"This lab is to explore running Hyperledger distributed ledgers under the
[Shadow simulator](https://github.com/shadow/shadow). It began as a research
internship during the summer of 2018 and seeks to provide a tool for doing
research on consensus algorithms, smart contracts, scaling and other blockchain
related research topics. "

Did the summer internship yield any code? Looking briefly at shadow, looks like you may create plugins for one or more of our dlts. Any specific plans? Like fabric? Sawtooth? etc. I see that they have a bitcoin plugin. What about plans to modify shadow itself? What are those plans?
Like Arnaud says, there has to be some more meat there, nothing detailed but some short term plans.
 We could also collaborate with PSWG as they have moved into the next phase. A network simulator would be a great thing to have.
About the suitability of LF staff sponsoring projects, I have no objections, but would like to see the charter reworded to admit this and tsc informed of this change and get some kind of nod from them.
As Arnaud stated, this is an exciting project and I am in support. However we have to be aware of the features of shadow especially the following text from the FAQ (which I am sure you are, but reproduced here for the benefit of our lab stewards): From the shadow FAQ.
Shadow is a network simulator/emulator hybrid. It runs real applications, but it simulates network and system functions thereby emulating the kernel to the application. **The suitability of Shadow to your problem depends upon what exactly you are trying to measure. If you are interested in analyzing changes in application behavior, e.g. application layer queuing, failure modes, or design changes, and how those changes affect the operation of the system and network performance, then Shadow seems like a very good choice (especially if you want to minimize work on your end)**. If your research relies on, e.g., the accuracy of specific kernel features or kernel parameter settings, or dynamic changes in Internet routing, then Shadow may not be the right choice as it does not precisely model these behaviors. Shadow is also not the best at measuring cryptographic overhead, so if that is desired then it should probably be done more directly as a separate research component.

**Comment by lehors** [comment]
I will make a motion to the TSC to officially include the staff into the list of people who can sponsor a lab. I don't expect this to be controversial..
In the meanwhile, it'd be good to have a bit more clarity on what the project entails.

**Comment by dhuseby** [comment]
I understand that the intent was not to have staff as sponsors.  I put myself down despite that fact because I wanted to get this moving.  There's nobody in our community that is thinking along these lines that would be an obvious candidate to sponsor.  So rather than let this die on the vine, I stepped in.

I will add more to the description with the exact roadmap.  The summer internship didn't really result in any code for a number of reasons but the most important one was that our blockchains don't like to be compiled outside of their neat little docker containers.  My intern Martin ran experiments to see if Shadow supported the Rust, Python, and Golang runtimes out of the box.  The answer is "no" in all cases.  Shadow does not emulate some of the pthread_mutex_attr API calls that is required by all three runtimes.  C++ networking apps will run under Shadow out of the box.  So the rest of the summer was spent on getting Iroha to build outside of the docker container.  We now have the build steps for that and the next step is to capture all of that in the repo.

The project is now me, Martin, Tapasweni Pathak (active open source developer), and two students from Turkey that just joined.  We already have an incoming pull request from Tapasweni and I have some queued up to land as well.  I wrote a set of patches for Shadow that make it support Rust out of the box that I will be upstreaming soon, so HL Indy isn't too far fetched anymore.

To answer Vipin's questions, we chose Shadow specifically because it is used to test the Tor and Bitcoin networks already.  It was the Bitcoin simulation that originally piqued my interest.  All of the plugin code for Tor and Bitcoin is open source as well as Shadow itself.  One of the nice features of Shadow is its ability to cluster across multiple machines to do simulations of thousands of nodes.  The main goal for using Shadow is to do lab-based experiments on the scalability of HL blockchains.  I think this would attract a lot of academics looking at decentralized systems.

**Comment by lehors** [comment]
Thanks for the additional info David. I made a motion to the TSC to officially include the staff into the list of people who can sponsor a lab. I don't expect this to be controversial and first responses confirm that.

**Comment by vipinsun** [comment]
David,
As to the comment about:
"There's nobody in our community that is thinking along these lines that would be an obvious candidate to sponsor".
The Performance and Scale working group is thinking along some of these lines. We were not aware of the Shadow work undertaken by the intern.  It might be helpful to reach out; I will also bring some of this to the attention of the group.
Work is being started also for getting code out of docker containers, mainly initiated by Mark Wagner. You might like to talk to him as well. The work already done for Iroha by your intern should inform that effort.
From your statements looks like there is some code (from Tapasweni & you and possibly the intern)
From the descriptions of Shadow it seems like it can only create those clusters on a single machine. I am aware that Shadow and the plugins that we create are open source (after all I quote from the FAQ which is part of this documentation). Definitely agree with you that this is a worthwhile effort and the right direction to be going in.
Vipin

**Comment by vipinsun** [comment]
David,
Thanks for being on the PSWG call and explaining shadow. As we saw, sponsorship can be done through Mark W, if there is push-back on staff sponsoring projects in lab.  
We need to be very clear about what shadow *can* do and what it *cannot* do. I will post on the PSWG rc channel. Hope we can get this ball rolling.
Thanks again,
Vipin

**Comment by dhuseby** [comment]
Yup, Mark has generously stepped forward to sponsor the shadow lab.  As for what shadow can and cannot do, the operative part from the documentation is:

> If your research relies on, e.g., the accuracy of specific kernel features or kernel parameter settings, or dynamic changes in Internet routing, then Shadow may not be the right choice as it does not precisely model these behaviors.

We are not using shadow for any of these things.  We are using it for application behavior under experimental conditions.

**Comment by ryjones** [comment]
@tkuhrt no strong opinion either way.

**Comment by lehors** [comment]
+1

**Comment by vipinsun** [comment]
I cannot login to github with no cell connectivity for SMS (needed for2FA).  But i have read the proposal and i have following comments.
I understand that the lab may not exit incubation. However its work products like plugins will be released into production. We need to reconcile this. Is there no source code related to this project with 4 maintainers?
+1 from me.
Thanks
Vipin

**Comment by dhuseby** [comment]
@vipinsun There is now: https://github.com/martmartinez91/shadow-hyperledger  The first few PR's have come in and there is active development ongoing.

**Comment by tkuhrt** [comment]
Two stewards have agreed that this should be a lab. I will create the Github repo and then merge this PR.

**Comment by dhuseby** [comment]
Great! thanks.

**Pull request merged**
