### PR TITLE
Proposal for Publish/Subscribe based Blockchain Interoperability

### PR DESCRIPTION
**Pull request by ghaemisr**
A blockchain interoperability solution for permissioned blockchain networks based on a publish/subscribe pattern.

Signed-off-by: Sara Ghaemi <ghaemi.sr@gmail.com>
Co-Authored-By: Rafael Belchior <rafael.belchior@tecnico.ulisboa.pt>

### CODE REVIEW

**Comment by RafaelAPB** [comment]
This lab supports a Hyperledger Summer Inteneship. I’m one of Sara’s mentor.

**Comment by ryjones** [comment]
> Rafael Belchior rafaelapb@users.noreply.github.com

is not a valid email address.

**Comment by ghaemisr** [comment]
@vipinsun Thank you for your comment. We will update the sponsor and the name of the project. 

Unlike Quilt which only focuses on payments between different blockchains, our project aims to tackle a specific use-case in blockchain interoperability. Upon successful completion of our project, the proposed solution has the potential to be added to Cactus as a feature. 

@ryjones Thank you for pointing that out. I updated the email address.

**Comment by lehors** [comment]
> Also the lab should have a specific name: The term blockchain-interoperability is too broad. Maybe interoperability-pubsub or something specific.
+1

**Comment by ghaemisr** [comment]
> Could you please also detail this specific use-case ?
> Together with a name which matches that use-case it should fix the issue with naming the lab too broadly.
 
Yes, definitely. I will make those changes.

**Comment by ghaemisr** [comment]
We are still looking for a sponsor for this project. Can any of you help us with that? Do you know anyone that can sponsor us?

**Comment by lehors** [comment]
> We are still looking for a sponsor for this project. Can any of you help us with that? Do you know anyone that can sponsor us?

That's all right. I'll be the sponsor.
<https://github.com/lehors> - TSC chair

But, please, do change the name of the lab (filename+name in the file) to something specific as suggested by Vipin. Something like interoperability-pubsub or maybe pubsub-interop for short would do.

**Comment by ghaemisr** [comment]
> That's all right. I'll be the sponsor.
> https://github.com/lehors - TSC chair
> 
> But, please, do change the name of the lab (filename+name in the file) to something specific as suggested by Vipin. Something like interoperability-pubsub or maybe pubsub-interop for short would do.

Thank you so much. I addressed all the requested changes in a new commit.

**Comment by ghaemisr** [comment]
> If you could do me a favor, please change the link "here".

I actually didn't know linking "here" is the wrong way of doing this. Thanks for letting me know. I fixed it.

**Pull request merged**
