### PR TITLE
MinBFT

### PR DESCRIPTION
**Pull request by ynamiki**
New Proposal: MinBFT.

### CODE REVIEW

**Comment by lehors** [comment]
It would be nice to make the github ids of the initial contributors actually links to the corresponding pages for convenience and add the email address or github id of the sponsor. Just to make it easier for people to see who's being this. But otherwise, I think this is a perfect fit for the labs. So, +1 for me!

**Comment by vipinsun** [comment]
Echo Arnaud's comments. So once that is fixed +1 from me as well.

**Comment by trbs** [comment]
Same here, +1

**Comment by ynamiki** [comment]
Thanks for your review. I will update the proposal later.

**Comment by tkuhrt** [comment]
Great! Once the proposal has been updated, it looks like we can go forward with creating a lab. I will be on the watch for an update.

**Comment by ynamiki** [comment]
I have updated the proposal to include the links for the initial contributors and the email address of the sponsor.

**Comment by ynamiki** [comment]
Thanks, we plan to bring over [our existing repository](https://github.com/nec-blockchain/minbft). I have confirmed that every commits excluding merge commits in the repo is signed-off at 91aba024a1dd4bbcf7a27991a3bbbf8f6b20bbea.

**Pull request merged**
