### PR TITLE
aries-sdk-mendix lab proposal submission

### PR DESCRIPTION
**Pull request by jorgefl0**
After feedback from the OWF technical advisory committee, it was advised that "wrapper" implementations to Aries should probably be maintained out of Hyperledger given the extensive Aries resources currently maintained out of this community.

## Checklist for Hyperledger Lab Proposal PR

- [ ] Read [README.md](https://github.com/hyperledger-labs/hyperledger-labs.github.io/blob/master/README.md) carefully
- [ ] Make sure your changes are committed with the proper sign-off
- [ ] Use the labs name as the PR title
- [ ] Copy the short description of the proposal as the description of the PR
- [ ] Remove this checklist section
- [ ] Submit your PR and the labs stewards will review your proposal
- [ ] Ask your sponsor to confirm sponsorship by stating so in a comment to the PR

### CODE REVIEW

**Comment by tkuhrt** [comment]
@jorgefl0 : Thanks for the proposal. For the existing repo, can you confirm which license and whether DCO sign off exists on all commits?

**Comment by jorgefl0** [comment]
> @jorgefl0 : Thanks for the proposal. For the existing repo, can you confirm which license and whether DCO sign off exists on all commits?

It does not look like the commit history includes DCO sign off. I'm guessing we'll have to recreate a new repo.

**Comment by tkuhrt** [comment]
> It does not look like the commit history includes DCO sign off. I'm guessing we'll have to recreate a new repo.

There is a way to [fix DCO retroactively](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) or we can create a new repo. Whichever you prefer.

**Review by tkuhrt — APPROVED** [review]
Confirming my sponsorship with my approval

**Review by nidhi-singh02 — APPROVED** [review]
This looks good, I approve the proposal.

**Comment by tkuhrt** [comment]
@jorgefl0 : Please let us know if you have been able to resolve the DCO on your existing repository. If so, we can do a transfer. If not, we will create a new repo for you and the team to use.

**Comment by tkuhrt** [comment]
Created https://github.com/hyperledger-labs/aries-sdk-mendix. Invited @jorgefl0 and @skullquake to the maintainers team.

**Pull request merged**
