### PR TITLE
Add fabric-client-flutter and fabric-server-node (2 repos).

### PR DESCRIPTION
**Pull request by 5sWind**
Signed-off-by: Hengming Zhang <fiveswind@gmail.com>

## Checklist for Hyperledger Lab Proposal PR

- [ ] Read [README.md](https://github.com/hyperledger-labs/hyperledger-labs.github.io/blob/master/README.md) carefully
- [ ] Make sure your changes are committed with the proper sign-off
- [ ] Use the labs name as the PR title
- [ ] Copy the short description of the proposal as the description of the PR
- [ ] Remove this checklist section
- [ ] Submit your PR and the labs stewards will review your proposal

### CODE REVIEW

**Comment by davidkhala** [comment]
We could highlight that the server has special purpose of supporting offline signing use case.

**Comment by 5sWind** [comment]
> We could highlight that the server has special purpose of supporting offline signing use case.

Yes, it's defined in Scope of Lab section, and I'll highlight that in the README.

**Comment by vipinsun** [comment]
Please follow the process outlined.
1. Separate the PR into two with the proper lab titles
2. Please have a little more detail in the description instead of just links to docs.
3. Sponsorship from ambassadors are allowed in the current charter? I will take a good look at this before signing off

**Comment by davidkhala** [comment]
> 3\. dors are allowed in the current charter? I will take a good look at this before signing off

In wiki I see sponsor could be `(i.e. a maintainer of one of the Hyperledger projects, a TSC member or a WG chair)`, so could I as TWGC Committee Board be a sponsor?

**Comment by 5sWind** [comment]
Close and reissue the PRs.

**Comment by 5sWind** [comment]
Redirect to #104 and #105.

**Pull request closed without merging**
