### PR TITLE
Unarchive the cordentity project

### PR DESCRIPTION
**Pull request by ryjones**
The covid cause to a high demand on digital identity technology. The Cordentity implements an efficient way to connect Indy and Corda so it makes possible to build sophisticated use cases where a verifier accepts credentials directly to a private decentralized network. The project was archived in 2019 due to low support, but in the mid/end of 2020 there is a number of external requests to unfreeze the project.

Signed-off-by: Alexander Kopnin <alkopnin@gmail.com>
Signed-off-by: Ry Jones <ry@linux.com>

### CODE REVIEW

**Comment by ryjones** [comment]
This replaces #159

**Review by tkuhrt — APPROVED** [review]
LGTM

**Review by trbs — APPROVED** [review]

**Review by lehors — APPROVED** [review]
Go for it! :-)

**Comment by ryjones** [comment]
https://github.com/hyperledger-labs/cordentity

**Pull request merged**
