### PR TITLE
Archive inactive labs

### PR DESCRIPTION
**Pull request by ryjones**
## Checklist for Hyperledger Lab Proposal PR

- [ ] Read [README.md](https://github.com/hyperledger-labs/hyperledger-labs.github.io/blob/master/README.md) carefully
- [ ] Make sure your changes are committed with the proper sign-off
- [ ] Use the labs name as the PR title
- [ ] Copy the short description of the proposal as the description of the PR
- [ ] Remove this checklist section
- [ ] Submit your PR and the labs stewards will review your proposal

### CODE REVIEW

**Comment by trbs** [comment]
Lgtm

Verstuurd vanaf mijn iPhone

**Comment by lehors** [comment]
Have we agreed on the timeframe after which in absence of activity we will archive a lab? Sorry, I can't remember and didn't find the answer on the wiki: https://wiki.hyperledger.org/display/labs

**Comment by tkuhrt** [comment]
From the [original proposal](https://docs.google.com/document/d/1VbgmlIqDnUnvjxSJ5QTUBV-Qn3eA7Gduw0edjYgDXIY/edit#)

> Stewards will also be responsible for curating the set of labs, moving to an archives space (see below) those that become dormant or unresponsive for an extended period (6+ months), or are explicitly deemed by the committers to be deprecated/obsoleted.

<snip>

> Deprecated, obsoleted, or dormant labs (as defined above) will be moved to a GitHub org “hyperledger-labs-archives” that signifies that the lab is no longer maintained. Labs in the archives still have committers, and if commits pick up they can be moved back out of the archives.

**Comment by lehors** [comment]
Thanks Tracy for digging this up! I had some recollection of having talked about this but couldn't find it. It'd be worth carrying this info into the wiki page.

**Comment by ryjones** [comment]
based on feedback on the mailing list I've withdrawn archiving SParts

**Comment by ryjones** [comment]
One note: I have been "archiving" the repos, which makes them read-only, contra the note above. My intention for stuff in the -archives orgs was they would be read-only artifacts.

**Comment by vipinsun** [comment]
> 
> 
> Thanks Tracy for digging this up! I had some recollection of having talked about this but couldn't find it. It'd be worth carrying this info into the wiki page.

I have added this to: https://wiki.hyperledger.org/display/labs/Hyperledger+Labs+Home

**Comment by ryjones** [comment]
> Lgtm 

@trbs Could you approve in the UI so I may merge?

**Comment by trbs** [comment]
> > Lgtm
> 
> @trbs Could you approve in the UI so I may merge?

Sorry for the late approval (on vacation with little internet access atm)

**Pull request merged**
