### PR TITLE
Created Donor Milk Submission

### PR DESCRIPTION
**Pull request by MariLeigh**
Signed-off-by: Marissa Iannarone <35410257+MariLeigh@users.noreply.github.com>

### CODE REVIEW

**Comment by MariLeigh** [comment]
@tkuhrt - sorry about that previous one. I hope this is correct. Full business case is here: https://wiki.hyperledger.org/groups/healthcare/donor_milk_transparency_and_traceability

**Comment by lehors** [comment]
It would be nice to make the github ids of the initial contributors actually links to the corresponding pages for convenience and add the email address or github id of the sponsor. Just to make it easier for people to see who's being this. We need to update the template accordingly. Otherwise, looks good to me.

**Comment by trbs** [comment]
@MariLeigh could you please put the link to the business case in `labs/milk-donor.md` as well ? 

That together with the (github) id's makes it +1 LTGM as well :-)

**Comment by MariLeigh** [comment]
I added the business case, please let me know if you need anything else.

**Comment by MariLeigh** [comment]
Hello,

I've added the URLs for the initial committer github ids , an email for
Nate, and the link to the business case. Please let me know if you need
anything else.

Thanks,
Marissa

Marissa Iannarone
Associate with Forum Solutions LLC <http://www.forumsolutionsllc.com/>
phone number: +01 (360) 525 4961
email: mari.iannarone@gmail.com

**Comment by lehors** [comment]
LGTM. Thanks.
+1

**Comment by tkuhrt** [comment]
Looks like we have enough Lab steward approvals. I will create a lab repo tomorrow.

**Comment by tkuhrt** [comment]
Lab created: https://github.com/hyperledger-labs/milk-donor. Invitations to initial committers sent.

**Pull request merged**
