### PR TITLE
Convector Framework

### PR DESCRIPTION
**Pull request by walmon**
Proposal to include Convector Framework to Hyperledger Labs.

### CODE REVIEW

**Comment by tkuhrt** [comment]
@walmon : It looks like your second commit failed to include the `-s` option to include the DCO signoff. Can you follow the instructions at https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/48/checks?check_run_id=25950638 to correct this?

**Comment by lehors** [comment]
The DCO needs to be addressed of course but otherwise I've looked into this before and I think it's a very interesting piece that fits well within the labs. Being the sponsor, I'll leave it to others to approve.

**Comment by vipinsun** [comment]
+1 via email.

**Comment by walmon** [comment]
Thanks @tkuhrt @lehors @vipinsun, I fixed the DCO problem with the PR. But I saw the current repo (that we want to keep) has DCO issues as well, please give me 1 or 2 days to fix it so that we can continue using Convector's repo.

**Comment by tkuhrt** [comment]
@walmon : Let us know. Getting the DCO corrected in the source repo will allow us to bring it over; otherwise, we will need to have you manually pull the source code over to a new repo.

**Comment by trbs** [comment]
+1

**Comment by walmon** [comment]
@tkuhrt : done, we signed every commit on the source repo to reuse it. https://github.com/worldsibu/convector

**Comment by tkuhrt** [comment]
I checked `git log` for both `master` and `develop` and I see log items that are not signed off.

**Comment by lehors** [comment]
@walmon unless you really want to carry over all of the history you do have the option to make a single commit with sign-off and be done with this. It's up to you.

**Comment by tkuhrt** [comment]
@walmon : Yes, we did mean -s. In order to transfer the https://github.com/worldsibu/convector repository over to the Hyperledger-Labs organization, someone with Admin permissions in the worldsibu organization will need to transfer the repo to Github user tkuhrt. Then I can transfer the ownership into the hyperledger-labs organization.

**Comment by tkuhrt** [comment]
@walmon : Any update on the transfer for the repository?

**Comment by ryjones** [comment]
@walmon any word?

**Comment by walmon** [comment]
Hello everybody, I'm sorry I forgot to write here after talking with Arnaud last year. We had a lot of doubts regarding the Labs and this is a really important project for us, so you may imagine that we have to be really careful. So initially we decided to stop the application. 

But we think that the Hyperledger Project can really benefit from Convector and the other way around. So we'd like to continue with the process. We'd love to see Convector graduate into a full-blown Hyperledger project, so it'd be great to know who to reach for us to focus on that.

We tried to transfer it to `tkuhrt` but we got an error since there's already a copy in your account @tkuhrt.

```
tkuhrt/convector already exists and You can only transfer a repository from an organization to yourself at this time
```

Let me know!

**Comment by ryjones** [comment]
If the DCO issue is resolved transfer it to me, @ryjones

Thanks

**Comment by walmon** [comment]
Done @ryjones !

**Comment by walmon** [comment]
Done @ryjones !

**Pull request merged**
