### PR TITLE
Overture Platform

### PR DESCRIPTION
**Pull request by tuvalusoftware**
Overture is a No-Code Development Platform (NCDP) that has been under research and development for 2 years (see video). Overture allows users to create programs, including  Ethereum smart contracts and Fabric chaincode using a drag-and-drop visual  languages.  Contracts can be deployed directly from the platform to Ethereum, Hyperledger Fabric or any EVM based blockchain. Before a contract is deployed it undergoes a rigorous formal verification process using state of the art formal methodologies . Our technology uses several never before seen inventions that allow us to add never before seen capability to blockchain including the ability make the cost of running a process on blockchain independent of the  complexity of the process and the ability to use advanced for Our roadmap includes using Reinforcement Learning and providing integration with Apache Camel and Spring integration to achieve our vision of allowing companies to transparently add blockchain capabilities-Trustlessness and Transparency - to business processes with minimum blockchain knowledge or skills requirements.  Our roadmap also includes performance tuning our application and deploying to kubernetes cloud. 

https://www.youtube.com/watch?v=njce9Q9hhMc&feature=youtu.be

### CODE REVIEW

**Comment by lehors** [comment]
@tuvalusoftware Do you intend to pursue this? Do you need help on how to proceed?

**Comment by vipinsun** [comment]
@tuvalusoftware Please read the readme file:
You have everything needed to commit to a lab, except
1. A copy of your proposal under the labs subdirectory (you can call it overture.md)
2. A sponsor. see guidelines for sponsor below.
Please see the quote below:


Fill out the Proposal Template and save it into the labs subdirectory under the name of your lab, such as mynewlab.md. It is expected that your lab repository will have the same name so keep that in mind.

In the Proposal Template, there is an entry for sponsor(s). The sponsor(s) are responsible for reviewing the proposal. Sponsors do not have a responsibility beyond this; ongoing work like contributing code or reviews is not tied to their role as sponsors. In reviewing the proposal, the sponsor(s) make sure that the proposal is cogent, and novel (in conception, proposed execution, or interested community). To find sponsors a. the proposers can use their connections to existing projects and ask maintainers b. find working groups or projects with affinities to the proposed lab and pitch the project (good to have the template already filled out) in associated channels and or mailing lists. The WG chairs emails, the maintainers contacts etc. can be found on the wiki or github. Make personal appeals if you can.

Commit your changes with proper sign-off. This means that your commit log message must contain a line that looks like the following one, with your actual name and email address:

 Signed-off-by: John Doe <john.doe@example.com>

Adding the -s flag to your git commit command will add that line automatically. You can also add it manually as part of your commit log message or add it afterwards with git commit --amend -s.

Submit a Pull Request.

**Comment by tuvalusoftware** [comment]
> @tuvalusoftware Do you intend to pursue this? Do you need help on how to proceed?
Hi, 
I do indeed intend to pursue this.

**Comment by tuvalusoftware** [comment]
> @tuvalusoftware Do you intend to pursue this? Do you need help on how to proceed?

Yes I would continue with this. Not sure who can be a sponsor

**Comment by tuvalusoftware** [comment]
> @tuvalusoftware Please see the readme file : https://github.com/hyperledger-labs/hyperledger-labs.github.io
> 
> You have everything needed to commit to a lab, except
> 
> 1. A copy of your proposal under the labs subdirectory (you can call it overture.md)
> 2. A sponsor. see guidelines for sponsor.
> 3. A DCO signoff

> @tuvalusoftware Do you intend to pursue this? Do you need help on how to proceed?

@lehors I would like to proceed. Not sure how

**Comment by vipinsun** [comment]
Quoted: The sponsor(s) are responsible for reviewing the proposal. Sponsors **do not** have a responsibility beyond this; ongoing work like contributing code or reviews is not tied to their role as sponsors. In reviewing the proposal, the sponsor(s) make sure that the proposal is cogent, and novel (in conception, proposed execution, or interested community). To find sponsors a. the proposers can use their connections to existing projects and ask maintainers b. find working groups or projects with affinities to the proposed lab and pitch the project (good to have the template already filled out) in associated channels and or mailing lists. The WG chairs emails, the maintainers contacts etc. can be found on the wiki or github. Make personal appeals if you can.

In case you have difficulty finding a sponsor using the above methods, let me know.

**Comment by vipinsun** [comment]
First thing to do is to create a fork and update the labs/overture.md - if you need sponsor, I can take a look at that proposal and sign on as sponsor. 
Make sure that your commits are signed off. 
You can then submit a PR for the creation of the lab.
If you have existing code then bring that in with a DCO signoff as well.

**Pull request closed without merging**
