### PR TITLE
Private transaction families

### PR DESCRIPTION
**Pull request by sgurary**
Signed-off-by: Shefy Gur-Ary <shefy.gurary@intel.com>

### CODE REVIEW

**Comment by sgurary** [comment]
Hi @tkuhrt 
The tag  @hyperledger-labs/lab-stewards  leads to 404 page
Thanks, Shefy

**Comment by tkuhrt** [comment]
@vipinsun @lehors @trbs @ryjones : Please comment on this lab. It has been a while since this lab was originally created and we have had a lot of DCO issues. @dcmiddle has already approved this in the previous PR.

**Comment by ryjones** [comment]
This looks good to me.

**Comment by ronenshemtov** [comment]
Thanks everyone.
How do we proceed from here? (i.e. upload the code, documentation)
Can we assume that the following URL is the link to the lab repository?
https://github.com/hyperledger-labs/private-transaction-families

**Comment by sgurary** [comment]
Hi @ronenshemtov,
I think the link is my fork:    https://github.com/sgurary/hyperledger-labs.github.io

@tkuhrt   - when is the pull request considered approve?
Can we start to upload the files to https://github.com/sgurary/hyperledger-labs.github.io ?

**Comment by tkuhrt** [comment]
It looks like we have one +1 on this proposal. We need one more, and then we can create the lab repository. @lehors @vipinsun @trbs : any feedback on this proposal?

**Comment by vipinsun** [comment]
LGTM

**Comment by ronenshemtov** [comment]
@yoni-wolf have uploaded the files and documents to:
https://github.com/yoni-wolf/private-tranaction-families 

@tkuhrt , Can you please confirm if it can be pulled into the new lab (Private-transaction-families)?

**Comment by lehors** [comment]
+1

**Comment by tkuhrt** [comment]
Created https://github.com/hyperledger-labs/private-transaction-families

**Pull request merged**
