### PR TITLE
Create fresh-air.md

### PR DESCRIPTION
**Pull request by m3m3m3m3**
Hello, 
I am attachinng a pull request, for Fresh Air.
Have a nice day

### CODE REVIEW

**Comment by tkuhrt** [comment]
Hi, @m3m3m3m3. Thanks for the PR. A couple of things. All commits to this repository require that you use the `-s` option to sign off the commit. You should be able to do this by doing the following (assuming that you only have a single commit on your branch):
```
git commit --amend -s
```

If not, you will need to squash your commit into a single commit and sign off.

Also, it is required that you fill in the **Initial Committers** and **Sponsor** sections.

**Comment by vipinsun** [comment]
Also please fill out the Pre-Existing repository. 
It might also help to rework the various sections removing some of "manifesto" style remarks and focusing on Engineering. Especially if your aim is to attract people to your lab there needs to be clarity of thought and an achievable goal clearly stated; I can help with this if we can have a conversation. I would focus on the aspects of "space" and "Position" after re-iterating the "time" aspect in the TimeStamp (or chronological ordering) service which is what the Blockchain really is (as you state).

**Comment by lehors** [comment]
So, why did you chose to close this?

**Comment by m3m3m3m3** [comment]
Dear Arnaud,

It has been not clear for new user how to simply register the project.

First. The hyperledger instruction says: fork, then as I was using github via web I pressed fork button,
buy hyperledged answered that I should have not used it, because then I was working on a local copy.
then guessing what button to press then was edit, create a .md, and pull it.

then I received the commentaries with some command line commit.
looking in google it says that it is not possible to do this github command line on web browser.

then looking for the command I installed github for desktop window. and git
but it says no valid fork.
so, for a fresh refresh then I delete it.

And tried installed again with another name.
but when publishing it, now github says permission error.

so, it was like walking blind in try-error.

best

Looking In google it said the command requested to run can not be

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request closed without merging**
