### PR TITLE
Nephos

### PR DESCRIPTION
**Pull request by alexvicegrab**

### CODE REVIEW

**Comment by trbs** [comment]
Besides the DCO error the PR is +1 LGTM from me. 

FYI: we also have ‘fabric-vms-provision’ which is similar but different :-) 

Is it a goal to maybe support other (hyperledger) projects in the future as well ?

**Comment by lehors** [comment]
Same for me. I do hope that the different people working in that space make the effort to understand how what they do compare and whether they could converge on anything so that we all get the most benefit out of all this energy.

**Comment by alexvicegrab** [comment]
Thank you, was away yesterday, fixed sign-off.

@trbs, yes, aware of `fabric-vms-provision`, which is interesting but addresses one component (e.g. a peer) per VM.

We focus on Kubernetes deployments, which allow us to also deploy other components to the same VMs (e.g. collocating a Kafka/Zookeeper/Orderer to the same VM), which reduces costs associated with maintaining a fabric network. Kubernetes also automates self-healing, so that Orderers/Peers are restarted in another server automatically if the VM/bare-metal they are hosted on dies.

Regarding supporting other projects, currently we support `Fabric` and (the now almost defunct) `Composer`. We are happy to receive PRs for deploying other networks, and some of the functionality, I'm confident (e.g. the CA registering/enrolling, Helm installing/checking, K8S configmap/secret creation, etc.) is reusable for other purposes.

@lehors agreed. We are in contact with the `Cello` team, hoping they will re-use/contribute to our back-end library to help provision the front-end/administrative part on Kubernetes. Much like `Umbra` does for for cryptography, we hope to be a reusable library by other projects where possible.

Unfortunately, there is no standard for deploying to Kubernetes, and some issues remain (e.g. Chaincode containers are not managed by K8S yet, hopefully to be addressed by Fabric v2.0).

Furthermore, we have been active in helping educate/develop the community on this specific niche, by releasing:

* A webinar on deploying Hyperledger Fabric on Kubernetes
* A workshop on the Hyperledger Global Forum

**Comment by vipinsun** [comment]
LGTM+1 and happily we see the differences between the two projects with more of an explanation from @alexvicegrab . Also the DCO checks have passed.

**Comment by ryjones** [comment]
LGTM

**Pull request merged**
