### PR TITLE
Hyperledger Fabric Builder for Kubernetes proposal

### PR DESCRIPTION
**Pull request by jt-nti**
External builder enabling Hyperledger Fabric peers to launch containerized chaincode using Kubernetes.

Sponsor: @lehors

### CODE REVIEW

**Comment by mbwhite** [comment]
I support this as well

**Review by tkuhrt — APPROVED** [review]
Other than the few missing DCO sign-offs on the existing repository, this LGTM.

**Comment by jt-nti** [comment]
I've prepared a branch with the missing DCO sign-offs ready for if the proposal is approved...

https://github.com/jt-nti/fabric-builder-k8s/commits/labs-dco

**Comment by denyeart** [comment]
I support this lab as well. This lab will complement fabric-operator to provide a complete kubernetes solution for base Fabric + Chaincode.

**Review by lehors — APPROVED** [review]
LGTM

**Pull request merged**
